app = "spencerduballcom-stage"
primary_region = "ord"
swap_size_mb = 512

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[mounts]
  source = "sdc_stage_data"
  destination = "/data"
  initial_size = "1GB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/" # TODO: Update this to /healthcheck and follow the Remix indie template
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"